MANIFEST.in

A few text files were missing from the source dist because they weren't in the manifest.
This fixes #327.

Add needed files to manifest

---

sagenb/notebook/worksheet.py

I strongly dislike code like
```
except Exception as msg:
print "Error copying file from worksheet process:", msg
```
Such error messages throw away the most useful information of an exception, namely the traceback.
Then also simplify the code by changing the copy + unlink to a move.

Simplify moving files from worksheet to cell

---

sagenb/notebook/cell.py

Currently HTML from html command is inserted into a `<pre>` block which means that you actually don't see real HTML output corresponding to your code. It also leads to extra dances for MathJax, we have our own parser for $ that replaces them with `<script>` tags. And I could not figure out how to turn on processing of environments. (My use case here: output a sequence "explanation formula explanation formula ..." which works way better in MathJax and LaTeX if each formula is a separate formula, rather than combining everything into a single math object.)
The change here is to wrap into `<pre>` every block which is NOT html - then we mostly have old behaviour, but HTML processing is now sensible and consistent with cell and cloud interfaces. (In particular, math environments are …

Do not wrap HTML output in <pre>

---

sagenb/interfaces/expect.py

In pexpect 3 and up `TIMEOUT` does not modify `.before`! Therefore we do not need to accumulate the output of `so_far`.
This change is necessary to upgrade `pexpect` at http://trac.sagemath.org/ticket/10295

This is a change needed to support pexpect 3 and  up

---

sagenb/interfaces/expect.py

Reverts sagemath/sagenb#351 temporarily to enable easier testing of downstream Sage ticket.

Revert "This is a change needed to support pexpect 3 and  up"

---

sagenb/data/sage/html/docs.html
sagenb/data/sage/html/error_message.html
sagenb/data/sage/html/history.html
sagenb/data/sage/html/notebook/afterpublish_window.html
sagenb/data/sage/html/notebook/base.html
sagenb/data/sage/html/notebook/cell.html
sagenb/data/sage/html/notebook/download_or_delete_datafile.html
sagenb/data/sage/html/notebook/edit_window.html
sagenb/data/sage/html/notebook/guest_worksheet_page.html
sagenb/data/sage/html/notebook/plain_text_window.html
sagenb/data/sage/html/notebook/print_worksheet.html
sagenb/data/sage/html/notebook/specific_revision.html
sagenb/data/sage/html/notebook/text_cell.html
sagenb/data/sage/html/notebook/worksheet.html
sagenb/data/sage/html/notebook/worksheet_page.html
sagenb/data/sage/html/settings/notebook_settings.html
sagenb/data/sage/html/worksheet_listing.html
sagenb/flask_version/base.py
sagenb/flask_version/worksheet.py
sagenb/notebook/cell.py
sagenb/notebook/challenge.py
sagenb/notebook/notebook.py
sagenb/notebook/template.py
sagenb/notebook/worksheet.py

The Jinja2 *automatic autoescape* has been enabled. Now the flask application adopts the Flask defaults and the Jinja2 environment is initialized  by the `flask.Flask` class. Now, any externally generated html must be declared explicitly as `safe` not to be escaped. This should help to make the Notebook more secure.
Does that solve any problem related to #319?
This changeset include non trivial changes and **should be tested intensively**. Several new bugs are expected.

Improved solution to #318

---

sagenb/flask_version/worksheet.py
sagenb/notebook/docHTMLProcessor.py

As @kcrisman pointed out in #324, the new `autoescape` default for jinja2 templates breaks some live docs. Here is a possible solution to be tested. This solution does not break the fix for the *hidden* bugs found in #324 during the discussion of the problem.

Live docs problems with autoescaping

---

sagenb/notebook/docHTMLProcessor.py

I've adapted the docs to the new unicode strings generated `sagenb.notebook.docHTMLProcessor` classes. 
If you want the docs to remain unchanged, I could change the `sagenb.notebook.docHTMLProcessor` behaviour, but it has a cost in form of  `utf-8` encoding/decoding overhead for every evaluation cell in the imported document. Also a non-flask *unescaper* could be used, but I don't know if this will bring a new dependency for sagenb.

doctest in docHTMLProcessor fixed. Fix for #357

---

sagenb/flask_version/base.py
sagenb/flask_version/doc.py
sagenb/misc/misc.py
sagenb/misc/sphinxify.py

We should use the new doc output location (`SAGE_DOC`) variable from http://trac.sagemath.org/ticket/20030

Use SAGE_DOC

---

sagenb/notebook/interact.py

The doctest example
```
sage: interact(matrix)
```
should be removed:
1. it doesn't actually work
2. it's not a natural way of using `interact`
3. it breaks http://trac.sagemath.org/ticket/20016

Remove useless interact(matrix) example

---

sagenb/misc/misc.py
sagenb/notebook/worksheet.py
sagenb/testing/stress.py

With the move of Sage's `alarm()` to the new [cysignals](https://github.com/sagemath/cysignals) package, importing `alarm` and `cancel_alarm` gives a deprecation warning. This is harmless, but we should no longer import `alarm` from Sage.
The easiest solution is simply to use Python's `alarm()` function, which works fine.

Use Python's alarm() function

---

README.rst

Because of #371, webassets is no longer installed in Sage.

Document that webassets needs to be installed

---

sagenb/flask_version/worksheet_listing.py
sagenb/interfaces/reference.py
sagenb/misc/format.py
sagenb/misc/support.py
sagenb/notebook/notebook.py
sagenb/notebook/user.py
sagenb/notebook/worksheet.py

I have converted the syntax from "except *Error, msg" (python2-only) to "except *Error as msg" 
which is py2/py3 compatible. Sometime removing the msg, when it was not used.
Reference:
http://python-future.org/compatible_idioms.html

little cleanup of the except clauses (into python 2/3 compatible syntax)

---

sagenb/notebook/colorize.py

Using tuples as arguments is not allowed in py3.
I also removed a duplicate import of os and sys.

correct bad syntax in arguments of call in colorize

---

sagenb/misc/misc.py
sagenb/notebook/all.py
sagenb/notebook/compress/JavaScriptCompressor.py
sagenb/notebook/js.py
sagenb/notebook/notebook.py
sagenb/notebook/notebook_object.py
sagenb/notebook/worksheet.py

as another small step towards python3, convert some of the imports
to the python3 absolute or relative import syntax.
Also changed some `ur"""` ro `r"""`

some modernizing of imports, toward python3 compatible imports

---

sagenb/notebook/auth.py
sagenb/notebook/run_notebook.py
sagenb/simple/twist.py

I forgot to add two "as" in previous pull requests. And also parentheses are required in 3 cases.

turn again syntax of some except clauses to python3

---

sagenb/misc/misc.py

I am not sure that this does not break things, but this import seems quite useless here, and it is already imported in interact.py

remove an unused import of srange

---

sagenb/flask_version/base.py

This will make it work on distros, where jsmol is typically installed in /usr/share

Use SAGE_SHARE instead of SAGE_ROOT for jsmol path

---

sagenb/notebook/all.py

When running the notebook master branch with sage 7.2, we obtain things like this:
The cause is a bad relative import in commit https://github.com/sagemath/sagenb/commit/89d3285f01920a4d2f5788102c5795e223e88f3e and this pull request fixes it.

Bad relative import fixed

---

sagenb/notebook/worksheet.py

The commit https://github.com/sagemath/sagenb/commit/07de9c8df196e73f8e94a8ff39d02e7ee10a4c79 causes a circular import. This can be safely fixed by deleting the offending import (see [these lines](https://github.com/sagemath/sagenb/blob/master/sagenb/notebook/worksheet.py#L910-L936))

Circular import

---

sagenb/notebook/cell.py
sagenb/notebook/conf.py
sagenb/notebook/notebook.py
sagenb/notebook/worksheet.py

For py3 compatibility, we should not use `cmp` at all.
I changed `__cmp__` to `__lt__` (not clear to me if this is correct).
I also replaced sorting by comparison to sorting by key (more clearly correct, I think).

do not use cmp (for python3 compatibility)

---

sagenb/interfaces/reference.py
sagenb/notebook/colorize.py
sagenb/notebook/mailsender.py
sagenb/testing/HTMLTestRunner.py

as another small step towards py3 compatibility, let us modernize the imports of StringIO and cStringIO

import StringIO and CStringIO in py2/3 compatible way

---

sagenb/data/sage/html/notebook/download_or_delete_datafile.html

In Sage-7.4 Notebook, Jinja2 replaces the HTML markup "<" and ">" by "&lt;" and "&gt;" respectively. In this commit a Jinja2 filter "safe" is used as suggested [here](http://flask.pocoo.org/docs/0.11/templating/#controlling-autoescaping).

Fix hyperlinks on datafile page

---

sagenb/notebook/notebook.py

This fix is to address the issue [discussed on the mailing list](https://groups.google.com/d/topic/sage-support/EK9nOmx4lsQ/discussion).
In Sage-7.4 the Notebook cannot read the text files with UTF-8 encoding (and perhaps, other 8-bit encodings too).
The idea of the proposed patch is first to try to decode the text as UTF-8, and if it does not work, fall back to Latin-1 encoding. This is not a graceful solution indeed, and is definitely not a smart thing to do.
However, in this case even if the text file is not in Latin-1 encoding, but in some other (let's say, in cp1251), the Notebook will still print the file to the screen instead of just saying "500: Internal server error." In such case the user will _see_ that the problem is the encoding of the text file.

Fix for UTF-8 data files

---

sagenb/data/sage/html/settings/user_management.html

Flask gets confused with original `url_for('users')` call as it does not know where to find the `users` endpoint. This issue can be fixed by addressing the local blueprint endpoint by prefixing a dot:
> In case blueprints are active you can shortcut references to the same blueprint by prefixing the local endpoint with a dot (.). ([Flask 0.12 documentation](http://flask.pocoo.org/docs/0.12/api/#flask.url_for))
Four lines calling `url_for` that result in a url build error from Flask are fixed to call the local endpoint.
Resolves #420.

Fix `url_for` call to reference local blueprint endpoint (fixes #420)

---

sagenb/flask_version/base.py

In order for the new Three.js viewer to work offline in Sage notebooks, there needs to be a server path to the JavaScript files. This appears to be the place to add it, but correct me if I'm wrong.
Reference: https://trac.sagemath.org/ticket/22488

Add path to threejs

---

sagenb/misc/sphinxify.py

This is a change needed in order to support changes I'm proposing to Sage in https://trac.sagemath.org/ticket/21732
Those changes haven't been approved yet though, so obviously this PR should not be merged until something is finalized in that Trac ticket.  Ideally, sagenb should probably not rely on Sage, or SAGE_DOC_SRC/SAGE_SRC at all for this, and I'd be in favor of a more extensive PR for sagenb to just include its own Sphinx configuration files for this purpose.  But for now this is the simplest solution.

Updated built-in sphinxify routine to support proposed changes in Sage

---

sagenb/flask_version/base.py

The old `flask.ext.xyz` syntax was deprecated for a while and is now causing errors with the latest flask.

Use new flask import syntax

---

sagenb/misc/misc.py

I'm not sure what the original intention behind the `except NameError` was (@fchapoton?). 326b9b074a looks like it was just a leftover of a refactoring. Either way it is a syntax error.
@fchapoton is the semantic right?

Fix syntax error

---

sagenb/misc/support.py
sagenb/notebook/docHTMLProcessor.py

because this is causing a failure in sage3 documentation build
**BEWARE** : I have no idea if this works or not..
see https://patchbot.sagemath.org/log/0/Ubuntu/18.04/x86_64/4.15.0-20-generic/petitbonum/2018-06-11%2009:26:28?plugin=docbuild

some care for imports (for python3)

---

sagenb/data/sage/html/login.html
sagenb/data/sage/html/worksheet_listing.html
sagenb/message.pot
sagenb/translations/de_AT/LC_MESSAGES/messages.po

As discussed in https://trac.sagemath.org/ticket/25852. I'm unsure how the localization and templating works. Am I doing this right?

Add deprecation warning

---

sagenb/flask_version/worksheet.py

Current behavior of worksheet_publish() returns '500 Internal error' (see https://ask.sagemath.org/question/42319/500-internal-server-error-on-reading-data-files-and-on-publishing-worksheets/). This is an attempt at solving the problem. I'm not 100% sure this is the right way, but the problem is gone and it appears that Sage behaves properly now.
Any feedback is welcome.

Use existing url_for_worksheet() for redirects
