sagenb/interfaces/expect.py, sagenb/notebook/notebook_object.py
See Sage Trac #11679 and Github issue #32
=> Allow different directory for server_pool communication

sagenb/notebook/worksheet.py
=> Remove unneeded imports

sagenb/data/sage/js/canvas3d_lib.js
I propose a few changes, in coordination with current work on trac ticket #12212. This will allow to display mesh surfaces with one color per face. And this also fills the surface
=> enrich canvas3D so that faces can be filled and colored

sagenb/notebook/notebook_object.py
They were in math markup not code markup
=> Fix formatting for login arguments

sagenb/notebook/worksheet.py
=> Copy instead of move such that owner is correct

sagenb/interfaces/expect.py
New pull request for http://trac.sagemath.org/ticket/10295 and http://trac.sagemath.org/ticket/19616.
=> Restore change for pexpect 4+ upgrade.

sagenb/misc/misc.py, sagenb/notebook/interact.py
Fixes for http://trac.sagemath.org/ticket/20094 (but should work with or without that ticket).
=> Fixes for Cythonized srange(), Sage Trac #20094

sagenb/notebook/interact.py
turning all print to python3 compatible syntax in one file (others in other pull requests)
=> turn print into python3 format

sagenb/notebook/challenge.py
step2 (I will try to do all th rest in one stroke)
=> turning again print to py3 in challenge

sagenb/misc/format.py, sagenb/notebook/docHTMLProcessor.py, sagenb/notebook/misc.py, sagenb/notebook/template.py
these are the minimal necessary changes so that tests pass in sage
=> several conversions of print to python3 syntax

sagenb/interfaces/reference.py, sagenb/misc/misc.py, sagenb/misc/remote_file.py, sagenb/notebook/auth.py, sagenb/notebook/jquery.py, sagenb/notebook/mailsender.py, sagenb/notebook/notebook.py, sagenb/notebook/run_notebook.py, sagenb/notebook/sage_email.py, sagenb/notebook/smtpsend.py, sagenb/simple/twist.py, util/apply-hg.py
I have converted some (but of course not all) instances of print to a shape that will work and give the same result in python2 and python3.
=> a bunch of print converted to python2/3 compatible style

sagenb/flask_version/worksheet_listing.py, sagenb/interfaces/expect.py, sagenb/misc/comments2rst.py, sagenb/misc/misc.py, sagenb/misc/support.py, sagenb/notebook/css.py, sagenb/notebook/interact.py, sagenb/notebook/notebook.py, sagenb/notebook/sagetex.py, sagenb/notebook/smtpsend.py, sagenb/notebook/user_manager.py, sagenb/notebook/worksheet.py, sagenb/storage/filesystem_storage.py, sagenb/testing/selenium/selenium.py
as a very small and easy step towards python3 compatibility
=> putting raise statements to python3 standard

sagenb/flask_version/worksheet_listing.py, sagenb/interfaces/expect.py, sagenb/misc/comments2rst.py, sagenb/misc/misc.py, sagenb/misc/support.py, sagenb/notebook/conf.py, sagenb/notebook/css.py, sagenb/notebook/docHTMLProcessor.py, sagenb/notebook/interact.py, sagenb/notebook/keyboards.py, sagenb/notebook/notebook.py, sagenb/notebook/sagetex.py, sagenb/notebook/smtpsend.py, sagenb/notebook/template.py, sagenb/notebook/user.py, sagenb/notebook/user_manager.py, sagenb/notebook/wiki2html.py, sagenb/notebook/worksheet.py, sagenb/storage/filesystem_storage.py, sagenb/testing/HTMLTestRunner.py, sagenb/testing/selenium/selenium.py
remove any use of has_key, which is python2 only, replaced by "x in y"
=> No has key

sagenb/flask_version/worksheet_listing.py, sagenb/interfaces/expect.py, sagenb/interfaces/reference.py, sagenb/misc/comments2rst.py, sagenb/misc/sphinxify.py, sagenb/misc/support.py, sagenb/notebook/cell.py, sagenb/notebook/colorize.py, sagenb/notebook/notebook_object.py, sagenb/notebook/user.py, sagenb/notebook/user_manager.py, sagenb/notebook/wiki2html.py, sagenb/notebook/worksheet.py, sagenb/simple/twist.py, sagenb/storage/filesystem_storage.py, sagenb/testing/grinder/logineval.py, sagenb/testing/selenium/selenium.py, sagenb/testing/stress.py
In this branch:
* some more prints (but not all) converted to python3. Some are kind of special, because the change    happen inside strings that will be fed to python somewhere
* a few raise that were missed in previous commits
* a few except, idem
=> some more print, raise and except to python2/3 compatible standard

sagenb/flask_version/worksheet.py, sagenb/misc/comments2rst.py, sagenb/misc/worksheet2rst.py, sagenb/notebook/notebook.py, sagenb/notebook/smtpsend.py, sagenb/notebook/tutorial.py, sagenb/testing/HTMLTestRunner.py, sagenb/testing/grinder/simpleeval.py, sagenb/testing/grinder/simpleeval_factor.py, sagenb/testing/grinder/simpleeval_multi.py, sagenb/testing/grinder/sstest.py, sagenb/testing/run_tests.py
taking care of the last instances of print not already changed to python3 syntax
I have used several times "from __future__ import print_function"
=> another bunch of print converted to python3

sagenb/flask_version/admin.py, sagenb/flask_version/authentication.py, sagenb/flask_version/base.py, sagenb/flask_version/doc.py, sagenb/flask_version/settings.py, sagenb/flask_version/worksheet.py, sagenb/flask_version/worksheet_listing.py
as another small step towards python3
=> change some imports to python3 compatible format (relative)

sagenb/misc/support.py
according to http://python-future.org/compatible_idioms.html, this should work both in py2 and py3
=> turn one exec to py2/py3 compatible syntax

sagenb/testing/HTMLTestRunner.py, sagenb/testing/run_tests.py, sagenb/testing/tests/__init__.py
some progress towards being able to import sagenb in python3, here in testing folder
=> some changes in imports in testing (towards py3)

sagenb/interfaces/__init__.py, sagenb/interfaces/reference.py, sagenb/storage/__init__.py, sagenb/storage/filesystem_storage.py
I have again modified some imports to make them compatible with py3
and also modernized an exec
All of this should work with python2.
=> some more py3 compatible imports, and one exec

sagenb/interfaces/reference.py, sagenb/misc/support.py, sagenb/notebook/cell.py, sagenb/notebook/challenge.py, sagenb/notebook/config.py, sagenb/notebook/jquery.py, sagenb/notebook/notification.py, sagenb/notebook/run_notebook.py, sagenb/notebook/sagetex.py, sagenb/notebook/server_conf.py, sagenb/notebook/smtpsend.py, sagenb/notebook/user.py, sagenb/notebook/user_conf.py, sagenb/notebook/user_manager.py, sagenb/notebook/wiki2html.py, sagenb/testing/stress.py
again some conversions of imports to py2/3 compatible format
plus an instance of backtick removed
plus an instance of octal changed
plus some instance of ur strings replaced by r strings
=> another bunch of py3 imports, and removed some ur and backticks

sagenb/misc/misc.py, sagenb/notebook/interact.py
otherwise the interact will be broken.
sorry for that. This was a wrong move from me.
=> re-introducing the import of srange

sagenb/notebook/interact.py
in notebook/interact, there were many old-style doctest continuations
=> some new style doctest continuation

sagenb/notebook/notebook.py
there were a few old-style doctest continuation ...
I replaced them by ....:
=> new style doctest continuation in notebook.py

sagenb/interfaces/expect.py
I have made a complete clean-up of this file:
* removing unused imports (not imported elsewhere from here)
including a StringIO (good not to have, thinking to python3)
* pep8 code clean-up
=> cleanup of expect.py (imports, pyflakes and pep8)

sagenb/testing/HTMLTestRunner.py, sagenb/testing/notebook_test_case.py, sagenb/testing/selenium/selenium.py, sagenb/testing/stress.py
the httplib and StringIO are maybe delicate changes.
still trying to move towards python3
=> some modern imports in testing folder

sagenb/flask_version/base.py, sagenb/flask_version/doc.py, sagenb/flask_version/worksheet.py, sagenb/flask_version/worksheet_listing.py, sagenb/misc/remote_file.py, sagenb/misc/worksheet2rst.py, sagenb/notebook/cell.py, sagenb/notebook/conf.py, sagenb/notebook/notebook.py, sagenb/notebook/run_notebook.py, sagenb/notebook/sage_email.py, sagenb/notebook/template.py, sagenb/notebook/user.py, sagenb/notebook/user_manager.py, sagenb/notebook/worksheet.py
in order to advance towards compatibility with python3, let us modernize all the imports that need it
=> futurize : absolute_imports

sagenb/notebook/cell.py
=> add __eq__

sagenb/misc/comments2rst.py, sagenb/misc/sphinxify.py, sagenb/misc/support.py, sagenb/notebook/applet.py, sagenb/notebook/keyboards.py, sagenb/notebook/notebook.py, sagenb/notebook/run_notebook.py, sagenb/notebook/user.py, sagenb/notebook/worksheet.py, sagenb/simple/twist.py, sagenb/storage/filesystem_storage.py
as another step for py3 compatibility, les us remove the calls to iteritems
=> No iteritems

sagenb/notebook/cell.py
apparently there is a bad invisible character here..
=> fix one bad character

sagenb/notebook/cell.py, sagenb/notebook/template.py, sagenb/notebook/worksheet.py
adding u prefix for some unicode strings in the doc
=> unicode had no u

sagenb/flask_version/admin.py, sagenb/flask_version/authentication.py, sagenb/flask_version/base.py, sagenb/flask_version/doc.py, sagenb/flask_version/settings.py, sagenb/flask_version/worksheet.py, sagenb/flask_version/worksheet_listing.py
another try to replace deprecated Module by Blueprint, not tested
=> Module >>> Blueprint

sagenb/storage/filesystem_storage.py
This was suggested by jhpalmieri in #425
=> one missing tmp_dir

sagenb/notebook/worksheet.py
trying to fix the comparison flaky doctest (maybe one also should add the total ordering decorator ?)
=> adding methods __ne__ and __gt__ for comparison of worksheets

sagenb/flask_version/admin.py, sagenb/flask_version/authentication.py, sagenb/flask_version/base.py, sagenb/flask_version/decorators.py, sagenb/flask_version/doc.py, sagenb/flask_version/settings.py, sagenb/flask_version/worksheet.py, sagenb/flask_version/worksheet_listing.py, sagenb/notebook/challenge.py, sagenb/notebook/conf.py, sagenb/notebook/notebook.py, sagenb/notebook/register.py, sagenb/notebook/server_conf.py, sagenb/notebook/template.py, sagenb/notebook/tutorial.py, sagenb/notebook/user_conf.py, sagenb/notebook/worksheet.py
for compatibility with more recent flask
=> change import flask.ext.babel to flask_babel

sagenb/misc/sphinxify.py
Reverts sagemath/sagenb#416
oops, sorry, my bad.
=> Revert "Updated built-in sphinxify routine to support proposed changes in Sage"

sagenb/notebook/notebook.py, sagenb/notebook/run_notebook.py, sagenb/notebook/smtpsend.py, sagenb/notebook/user_manager.py, sagenb/storage/filesystem_storage.py
in notebook.py and run_notebook.py
=> taking care of basestring for py3

sagenb/flask_version/base.py
This simple change seem to fix the known issue with flask update.
=> fix that allow to update flask

sagenb/misc/sphinxify.py
removing another import of `__builtin__`, using six instead
plus some small cleanup in the modified file
=> another python3 fix and cleanup

sagenb/flask_version/authentication.py
after a suggestion made by lgtm at https://lgtm.com/projects/g/sagemath/sagenb/alerts/?mode=list&severity=error&lang=python
=> one tiny detail in login

sagenb/flask_version/worksheet.py
as suggested by lgtm
https://lgtm.com/projects/g/sagemath/sagenb/
=> several cleanups

sagenb/notebook/interact.py
A failing doctest for the sage library on python 3 led me to this from https://trac.sagemath.org/ticket/27435.
=> notebook.interact.py: xrange -> range for python3
